community_name: "Community"
community_tagline: "CommunityEngine Rocks!"
community_description:  "The Best Place for People Who Love Communities"
support_email:  "support@community.com"
meta_description: 'A description of your community for use in META tags.'
meta_keywords: 'keywords for use in META tags'
sections_enabled: ['photos', 'posts', 'clippings', 'contests', 'categories', 'events']
show_advertising: false
closed_beta_mode: false
# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "en"

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
allow_anonymous_commenting: false
require_captcha_on_signup: false
#recaptcha_pub_key: YOUR_PUB_KEY
#recaptcha_priv_key: YOUR_PRIV_KEY
# uncomment these keys if you turn captcha on for commenting or signup

# for SEO reasons sometime you should control the robots on how they have to handle your content
# listing of stuff which points to single posts or entries should normally not been indexed,
# but the robot should follow the internal link to show the post
robots_meta_list_content: 'noindex,follow'
# the post itself should be indexed;
# when links are included and they point to external sites, the robot should not follow
robots_meta_show_content: 'index,nofollow'

reserved_logins: [
  'about',
  'account',
  'advertise',
  'ads',
  'application',
  'assets',
  'categories',
  'choices',
  'clippings',
  'clipping_images',
  'comments',
  'contests',
  'countries',
  'css_help',
  'events',
  'favorites',
  'faq',
  'featured',
  'forums',
  'friendships',
  'friendship_statuses',
  'home',
  'homepage_features',
  'images',
  'invitations',
  'javascripts',
  'login',
  'logout',
  'manage_photos',
  'messages',
  'metro_areas',
  'moderatorships',
  'new_clipping',
  'offerings',
  'photos',
  'polls',
  'popular',
  'popular_rss',
  'posts',
  'recent',
  'roles',
  'search',
  'signup',
  'sb_posts',
  'skills',
  'sitemap',
  'states',
  'stylesheets',
  'tags',
  'theme',
  'topics',
  'users',
  'votes']
